<script setup lang="ts">
import {computed,ref,onMounted,onUnmounted,watch} from 'vue';
import {Star,Map,Shirt,ShoppingBag,BookOpen,Volume2,VolumeX,ChevronRight,ArrowLeft,Lock,Play,Sparkles,Gift,Check,X,LogOut,Heart,Settings,Leaf,Trophy} from 'lucide-vue-next';
import Avatar from './Avatar.vue';
import type {Emotion} from './rig/pose';
import {outfits,accessories,getOutfit,suit,slots,slotNames,levels,islandNames,modeNames,modeIcons,completeOutfit,type Equipment,type Slot} from '../shared/catalog';
import {progress as p,currentUser as user,challenge as c,revision,request,refresh,action,NetworkError,type PublicQuestion} from './api';
const avatarEmotion=ref<Emotion>('idle'),reaction=ref(0);
const emote=(value:Emotion)=>{avatarEmotion.value=value;reaction.value++;};
const page=ref('home'),busy=ref(false),toast=ref(''),error=ref(''),auth=ref(false),authMode=ref('login');
const email=ref(''),password=ref(''),nickname=ref(''),resetToken=new URLSearchParams(location.search).get('reset');
const authMessage=ref(''),resetAvailable=ref(false),ready=ref(false),perform=ref(0),transform=ref(false),gift=ref(false);
const tutorialStep=ref(0),tutorialOpen=ref(false),freeSuit=ref('rabbit'),tutorialAnswer=ref(false);
const dressingSlots=slots.filter(s=>!['hair','body','skirt'].includes(s));
const dressingNames={...slotNames,pants:'下装'};
const selected=ref('rabbit'),filter=ref('全部'),preview=ref<Equipment|null>(null),mixSlot=ref<Slot|null>(null),shopTab=ref('套装');
const input=ref(''),feedback=ref(''),correctAnimation=ref(false),streak=ref(0),roundCompletions=ref(0);
const retry=ref<null|(()=>Promise<void>)>(null);const selectedLevel=ref<number|null>(null);const timers:ReturnType<typeof setTimeout>[]=[];
const later=(fn:()=>void,ms:number)=>{const t=setTimeout(fn,ms);timers.push(t);return t;};
const currentOutfit=computed(()=>getOutfit(p.value.equipment.top));
const shownEquipment=computed(()=>preview.value||p.value.equipment);
const shopOutfit=computed(()=>getOutfit(selected.value));
const selectedItem=computed(()=>accessories.find(a=>a.id===selected.value));
const unlocked=computed(()=>Math.min(18,Object.keys(p.value.stars).length+1));
const nextLevel=computed(()=>c.value&&!c.value.settled?c.value.level:unlocked.value);
const wish=computed(()=>p.value.wish?getOutfit(p.value.wish):null);
const filteredOutfits=computed(()=>outfits.filter(o=>(o.id!=='base'||page.value==='wardrobe')&&(filter.value==='全部'||o.series===filter.value)&&(page.value!=='wardrobe'||p.value.owned.includes(o.id))));
const filteredAccessories=computed(()=>accessories.filter(a=>(page.value!=='wardrobe'||p.value.owned.includes(a.id))&&(!mixSlot.value||a.slot===mixSlot.value)));
const heldQuestion=ref<PublicQuestion|null>(null),lastAnswer=ref<number|null>(null);
const q=computed(()=>correctAnimation.value&&heldQuestion.value?heldQuestion.value:c.value?.question);const mode=computed(()=>q.value?.mode||0);
const mastery=computed(()=>Object.entries(p.value.facts).filter(([,f])=>f.correct>=3&&f.challenges.length>=2&&f.recent.length>=2&&f.recent.every(Boolean)&&!f.weak));
const weak=computed(()=>Object.entries(p.value.facts).filter(([,f])=>f.weak));
const selectedInfo=computed(()=>selectedLevel.value?levels[selectedLevel.value-1]:null);
const isOwned=computed(()=>p.value.owned.includes(selected.value));
const canAfford=computed(()=>p.value.coins>=(selectedItem.value?.price??shopOutfit.value.price));
const mapPositions=[[12,71],[25,48],[37,70],[49,45],[62,67],[76,47],[88,25],[64,20],[39,18]];
function notice(text:string){toast.value=text;later(()=>toast.value='',3200);}
let audio:AudioContext|null=null;
function sound(win=true){if(!p.value.settings.sound)return;try{audio??=new AudioContext();void audio.resume();[0,.12,.24].forEach((delay,i)=>{const o=audio!.createOscillator(),g=audio!.createGain();o.type='sine';o.frequency.value=win?[523,659,784][i]!:330;g.gain.setValueAtTime(.045,audio!.currentTime+delay);g.gain.exponentialRampToValueAtTime(.001,audio!.currentTime+delay+.22);o.connect(g);g.connect(audio!.destination);o.start(audio!.currentTime+delay);o.stop(audio!.currentTime+delay+.24);});}catch{/* Sound is optional when the browser suspends audio. */}}
function celebrate(){emote('happy');perform.value++;sound();}
async function run(fn:()=>Promise<void>){if(busy.value)return;busy.value=true;error.value='';retry.value=null;try{await fn();}catch(e){const ex=e as NetworkError;error.value=ex.message;if(ex.status===401){auth.value=true;}else if(ex.status===409){await refresh().catch(()=>{});notice('已同步最新进度');}else if(ex.status===0||ex.status>=500)retry.value=()=>run(fn);}finally{busy.value=false;}}
function requireLogin(){if(!user.value){auth.value=true;authMode.value='register';return false;}return true;}
function navigate(to:string){page.value=to;mixSlot.value=null;avatarEmotion.value='idle';preview.value=null;error.value='';retry.value=null;feedback.value='';if(to==='shop'||to==='wardrobe'){selected.value=page.value==='wardrobe'?p.value.equipment.body:'rabbit';preview.value=suit(selected.value);} }
async function submitAuth(){await run(async()=>{authMessage.value='';if(authMode.value==='forgot'){const r=await request('/auth/forgot',{email:email.value});authMessage.value=r.message;return;}if(authMode.value==='reset'){await request('/auth/reset',{token:resetToken,password:password.value});authMode.value='login';history.replaceState({},'',location.pathname);authMessage.value='密码已更新，请重新登录';return;}await request('/auth/'+authMode.value,{email:email.value,password:password.value,nickname:nickname.value});revision.value=-1;await refresh();auth.value=false;if(!p.value.tutorial){tutorialOpen.value=true;tutorialStep.value=0;}});}
async function logout(){await run(async()=>{await request('/auth/logout',{});user.value=null;location.reload();});}
async function start(level=nextLevel.value){if(!requireLogin())return;if(!p.value.tutorial){tutorialOpen.value=true;return;}const id=crypto.randomUUID();await run(async()=>{await action('start',{level},id);selectedLevel.value=null;page.value='game';input.value='';feedback.value='';streak.value=0;preview.value=null;});}
async function finishTutorial(){const id=crypto.randomUUID();await run(async()=>{await action('tutorial',{id:freeSuit.value},id);tutorialOpen.value=false;page.value='home';doTransform(true);});}
function doTransform(openGift=false){gift.value=openGift;transform.value=true;celebrate();later(()=>{transform.value=false;gift.value=false;},p.value.settings.reducedMotion?600:openGift?3400:2400);}
function chooseSlot(slot:Slot|null){mixSlot.value=slot;selectProduct(selected.value);}
function selectProduct(id:string){if(id==='iron'&&mixSlot.value){notice('钢铁侠精绘部件尚未就绪，暂不支持混搭');return;}selected.value=id;if(outfits.some(o=>o.id===id))preview.value=mixSlot.value?{...p.value.equipment,[mixSlot.value]:id}:suit(id);else{const a=accessories.find(x=>x.id===id);if(a)preview.value={...p.value.equipment,[a.slot]:id};}perform.value=0;}
async function equip(){if(!requireLogin())return;const id=crypto.randomUUID();await run(async()=>{await action('equip',{id:selected.value,...(mixSlot.value&&!selectedItem.value?{slot:mixSlot.value}:{})},id);preview.value=null;doTransform();});}
async function buy(){if(!requireLogin())return;const purchase=crypto.randomUUID(),wear=crypto.randomUUID(),product=selected.value;await run(async()=>{await action('buy',{id:product},purchase);await action('equip',{id:product},wear);preview.value=null;doTransform(outfits.some(o=>o.id===product));notice('已兑换并穿戴，新的冒险造型！');});}
async function setWish(){if(!requireLogin())return;const id=crypto.randomUUID();await run(async()=>{await action('wish',{id:selected.value},id);notice('已放进你的心愿清单');});}
async function settings(key:'sound'|'reducedMotion'){if(!requireLogin())return;const id=crypto.randomUUID();await run(async()=>{await action('settings',{[key]:!p.value.settings[key]},id);});}
async function hint(){if(!c.value||!q.value)return;const data={challengeId:c.value.id,questionId:q.value.id},id=crypto.randomUUID();await run(async()=>{await action('hint',data,id);feedback.value='我们一起数一数，再试一次吧';});}
async function answer(value:number){if(!q.value||!c.value||busy.value||correctAnimation.value)return;heldQuestion.value=JSON.parse(JSON.stringify(q.value));lastAnswer.value=value;const data={challengeId:c.value.id,questionId:q.value.id,value},id=crypto.randomUUID();await run(async()=>{const r=await action('answer',data,id);if(r.feedback.correct){input.value='';correctAnimation.value=true;streak.value=r.feedback.first?streak.value+1:0;feedback.value=r.feedback.first?(streak.value===3?'连续答对 3 题，真棒！':'答对啦！小小进步 +1'):'这次记住啦！';sound();emote('happy');perform.value++;later(()=>{correctAnimation.value=false;feedback.value='';},p.value.settings.reducedMotion?250:950);if(c.value?.index===8){const settleId=crypto.randomUUID();await action('settle',{challengeId:c.value.id},settleId);roundCompletions.value++;later(()=>{page.value='result';celebrate();},1000);}}else{emote('sad');streak.value=0;input.value='';feedback.value='再想一想，你可以的！';}});}
async function finishPending(){if(!c.value)return;const id=crypto.randomUUID();await run(async()=>{await action('settle',{challengeId:c.value!.id},id);page.value='result';celebrate();});}
function keypress(e:KeyboardEvent){if(page.value!=='game'||![1,3].includes(mode.value)||busy.value||correctAnimation.value||auth.value)return;if(e.target instanceof HTMLInputElement)return;if(/^\d$/.test(e.key))input.value=(input.value+e.key).slice(0,2);else if(e.key==='Backspace')input.value=input.value.slice(0,-1);else if(e.key==='Enter'&&input.value)void answer(Number(input.value));}
function digit(s:string){if(s==='⌫')input.value=input.value.slice(0,-1);else input.value=(input.value+s).slice(0,2);}
function 口诀(a:number,b:number){const n=['','一','二','三','四','五','六','七','八','九'];const x=Math.min(a,b),y=Math.max(a,b),v=a*b;const result=v<10?'得'+n[v]:v===10?'一十':(v<20?'一十':n[Math.floor(v/10)]+'十')+(v%10?n[v%10]:'');return n[x]!+n[y]!+result;}
function factStatus(a:number,b:number){const f=p.value.facts[[a,b].sort((x,y)=>x-y).join('x')];return !f?'unseen':f.weak?'weak':mastery.value.some(([k])=>k===[a,b].sort((x,y)=>x-y).join('x'))?'mastered':'practiced';}
const visibility=()=>{if(document.visibilityState==='visible'&&user.value&&!busy.value&&page.value!=='game')void refresh().catch(()=>{});};
onMounted(async()=>{document.addEventListener('keydown',keypress);document.addEventListener('visibilitychange',visibility);if(resetToken){auth.value=true;authMode.value='reset';}try{const h=await request('/health');resetAvailable.value=h.resetAvailable;await refresh();}catch(e){if((e as NetworkError).status!==401)error.value=(e as Error).message;}finally{ready.value=true;}});
onUnmounted(()=>{document.removeEventListener('keydown',keypress);document.removeEventListener('visibilitychange',visibility);timers.forEach(clearTimeout);void audio?.close();});
watch(()=>p.value.settings.reducedMotion,v=>document.documentElement.classList.toggle('reduced-motion',v),{immediate:true});
</script>

<template>
<div class="app-shell">
 <header class="topbar">
  <button class="brand" @click="navigate('home')"><span class="brand-mark"><Star :size="26" fill="currentColor"/></span><span>星星乘法岛<small>STAR ISLAND</small></span></button>
  <nav aria-label="主导航"><button :class="{active:page==='home'||page==='game'||page==='result'}" @click="navigate('home')"><Map :size="19"/>冒险地图</button><button :class="{active:page==='wardrobe'}" @click="navigate('wardrobe')"><Shirt :size="19"/>我的衣柜</button><button :class="{active:page==='shop'}" @click="navigate('shop')"><ShoppingBag :size="19"/>星星商城</button></nav>
  <div class="top-actions"><span class="coin"><span>★</span>{{p.coins}}<small>星星币</small></span><button class="icon-btn" aria-label="切换声音" @click="settings('sound')"><Volume2 v-if="p.settings.sound" :size="19"/><VolumeX v-else :size="19"/></button><button class="parent-link" @click="requireLogin()&&navigate('parent')"><Settings :size="17"/>家长中心</button><button v-if="!user" class="small-login" @click="auth=true">登录</button></div>
 </header>
 <div v-if="error" class="error-banner" role="alert">{{error}}<button v-if="retry" @click="retry()">重试</button><button aria-label="关闭提示" @click="error=''"><X :size="16"/></button></div>
 <main v-if="page==='home'" class="home-page">
  <div class="page-heading"><div><span class="eyebrow">每一点进步，都闪闪发光</span><h1>你好，{{user?.nickname||'小冒险家'}} <span class="wave">✦</span></h1><p>穿上喜欢的外观，开启今天的乘法小冒险吧！</p></div><div class="learning-pill"><span>✧</span><div>小小步，也很棒<small>不用着急，按自己的节奏来</small></div></div></div>
  <div class="home-grid">
   <section class="hero-card" :style="{'--stage-color':currentOutfit.color}">
    <div class="card-top"><span class="tag"><span class="green-dot"></span>我的冒险家</span><span class="tiny">{{completeOutfit(p.equipment)==='mixed'?'专属混搭':currentOutfit.series+'系列'}}</span></div>
    <div class="character-stage" @click="celebrate()"><span class="stage-star s1">✦</span><span class="stage-star s2">✧</span><span class="stage-star s3">✦</span><div class="stage-orbit"></div><Avatar :equipment="p.equipment" :perform="perform" :emotion="avatarEmotion" :reaction="reaction" :reduced="p.settings.reducedMotion"/><span class="stage-note">点击角色，看看我的招牌动作</span></div>
    <div class="hero-name"><h2>{{completeOutfit(p.equipment)==='mixed'?'我的专属造型':currentOutfit.name}}</h2><p>{{currentOutfit.description}}</p></div>
    <div class="emotion-buttons" aria-label="试试小表情"><button @click="emote('happy')">✦ 开心</button><button @click="emote('blush')">♡ 害羞</button><button @click="emote('angry')">ϟ 小斗志</button></div><div class="hero-buttons"><button class="btn light" @click="navigate('wardrobe')"><Shirt :size="18"/>去换装</button><button class="btn cream" @click="celebrate()"><Sparkles :size="18"/>展示动作</button></div>
    <div class="wish-bar" v-if="wish"><div class="wish-thumb"><Avatar :equipment="suit(wish.id)" reduced/></div><div><strong>我的心愿 · {{wish.name}}</strong><small>{{p.owned.includes(wish.id)?'已经拥有，去试试新搭配吧':`还差 ${Math.max(0,wish.price-p.coins)} 星星币，就能带回家`}}</small><div class="mini-progress"><i :style="{width:Math.min(100,p.coins/wish.price*100)+'%'}"></i></div></div><button class="icon-btn" aria-label="查看心愿套装" @click="navigate('shop');selectProduct(wish!.id)"><ChevronRight :size="20"/></button></div>
    <button v-else class="wish-empty" @click="navigate('shop')"><Heart :size="20"/><span>挑一套喜欢的外观，许个小心愿</span><ChevronRight :size="18"/></button>
   </section>
   <div class="adventure-column">
    <section class="map-card"><div class="map-heading"><div><span class="eyebrow">我的冒险旅程</span><h2>今天，也向前一步</h2></div><span class="level-count"><strong>{{Object.keys(p.stars).length}}</strong> / 18 关</span></div>
     <div class="island-map"><img src="/art/map.webp" alt="有小树、蘑菇和木桥的乘法冒险群岛" class="map-background"><div class="map-mist"></div><div v-for="(name,i) in islandNames" :key="name" class="map-node-wrap" :style="{left:mapPositions[i]![0]+'%',top:mapPositions[i]![1]+'%'}"><button class="map-node" :class="{current:Math.floor((nextLevel-1)/2)===i,locked:i*2+1>unlocked,done:!!p.stars[i*2+2]}" :aria-label="`${name}，第${i*2+1}关`" @click="selectedLevel=i*2+1"><Lock v-if="i*2+1>unlocked" :size="15"/><Check v-else-if="p.stars[i*2+2]" :size="19"/><span v-else>{{i+1}}</span></button><span class="node-label" v-if="i===Math.floor((nextLevel-1)/2)||i===0||i===8">{{name}}</span></div><div class="map-legend"><span class="legend-dot"></span>9 座小岛 · 18 场小冒险</div></div>
     <div class="continue-card"><div class="level-icon">{{modeIcons[(nextLevel-1)%4]}}</div><div class="continue-info"><span>第 {{String(nextLevel).padStart(2,'0')}} 关 · {{islandNames[Math.floor((nextLevel-1)/2)]}}</span><h3>{{nextLevel>=17?'星星混合庆典':modeNames[(nextLevel-1)%4]}}</h3><small>8 道小挑战 <span>·</span> {{nextLevel>=17?'综合复习':`${levels[nextLevel-1]!.factor} 的乘法口诀`}}</small></div><button class="btn primary" :disabled="busy||!ready" @click="start()">{{c&&!c.settled?'继续挑战':'开始冒险'}}<ChevronRight :size="19"/></button></div>
    </section>
    <div class="lower-cards"><section class="encourage-card"><span class="little-icon">🌱</span><div><h3>慢慢来，你一直在进步</h3><p>答错也没关系，我们一起再试一次。</p><span>{{mastery.length}} 个口诀已熟悉 <span class="divider">/</span> {{Object.keys(p.facts).length}} 个口诀已练习</span></div></section><button class="collection-card" @click="navigate('shop')"><span class="mini-stars">✦ ✧</span><div><span class="eyebrow">冒险家的新衣</span><h3>下一套，会是谁？</h3><span>去星星商城看看 <ChevronRight :size="14"/></span></div><div class="collection-actor"><Avatar :equipment="suit('nezha')" reduced/></div></button></div>
   </div>
  </div>
  <footer class="home-footer"><Leaf :size="15"/>每天一点点，把口诀变成你的超能力。<span>完成 3 关后，记得让眼睛休息一下哦</span></footer>
 </main>

 <main v-else-if="page==='shop'||page==='wardrobe'" class="shop-page">
  <div class="page-heading"><div><span class="eyebrow">{{page==='shop'?'每一次努力，都值得被奖励':'今天，想成为怎样的自己？'}}</span><h1>{{page==='shop'?'星星商城':'我的衣柜'}} <span>✧</span></h1><p>{{page==='shop'?'喜欢的外观，可以先试穿。所有奖励都靠自己的小进步获得。':'已拥有的外观随心搭配，换上新衣再出发。'}}</p></div><button class="btn light" @click="navigate('home')"><ArrowLeft :size="18"/>回到冒险</button></div>
  <div class="shop-layout"><section class="fitting-card" :style="{'--stage-color':getOutfit(shownEquipment.top).color}"><div class="card-top"><span class="tag">{{preview?'试衣间':'当前穿戴'}}</span><span class="tiny">{{selectedItem?'自由搭配':shopOutfit.series+'系列'}}</span></div><div class="fitting-stage"><Avatar :equipment="shownEquipment" :perform="perform" :emotion="avatarEmotion" :reaction="reaction" :reduced="p.settings.reducedMotion"/><button class="show-action" @click="celebrate()"><Sparkles :size="17"/>看看招牌动作</button></div><div class="emotion-buttons" aria-label="试试小表情"><button @click="emote('happy')">✦ 开心</button><button @click="emote('blush')">♡ 害羞</button><button @click="emote('angry')">ϟ 小斗志</button></div><h2>{{selectedItem?.name||shopOutfit.name}}</h2><p>{{selectedItem?'小配饰，让你的冒险家更特别。':shopOutfit.description}}</p><small v-if="!selectedItem" class="action-label">{{shopOutfit.action}}</small>
   <div class="purchase-controls"><button v-if="selected==='iron'" class="btn primary full" disabled>精绘升级中 · 暂停兑换</button><button v-else-if="isOwned" class="btn primary full" :disabled="busy" @click="equip()"><Shirt :size="18"/>{{mixSlot?'穿到'+dressingNames[mixSlot]:'立即穿戴'}}</button><button v-else class="btn primary full" :disabled="busy||(!canAfford&&!!user)" @click="buy()"><span class="gold-star">★</span>{{selectedItem?.price||shopOutfit.price}} 星星币 · 兑换并穿戴</button><small v-if="selected!=='iron'&&!isOwned&&!canAfford" class="need-coins">还差 {{(selectedItem?.price||shopOutfit.price)-p.coins}} 币，完成关卡就能积攒</small></div>
   <button v-if="selected!=='iron'&&!selectedItem&&!isOwned" class="wish-button" @click="setWish()"><Heart :size="17" :fill="p.wish===selected?'currentColor':'none'"/>{{p.wish===selected?'已经是我的心愿':'设为我的心愿'}}</button>
   <div v-if="page==='wardrobe'" class="skin-mode"><button :class="{selected:!mixSlot}" @click="chooseSlot(null)">整套换装</button><span>{{mixSlot?'正在搭配：'+dressingNames[mixSlot]:'也可以挑一个部位单独换'}}</span></div><div class="equipment-slots" v-if="page==='wardrobe'"><button v-for="slot in dressingSlots" :key="slot" :class="{selected:mixSlot===slot}" @click="chooseSlot(mixSlot===slot?null:slot)"><span>{{dressingNames[slot]}}</span><small>{{accessories.find(a=>a.id===p.equipment[slot])?.icon||getOutfit(p.equipment[slot]).icon}}</small></button></div><p v-if="page==='wardrobe'" class="rig-note">精绘造型支持六类混搭；发型与表情随头部造型。</p><button v-if="mixSlot" class="wish-button" @click="run(async()=>{await action('unequip',{slot:mixSlot});preview=null})">卸下{{dressingNames[mixSlot]}}</button>
  </section><section class="catalog"><div class="catalog-tabs"><button :class="{active:shopTab==='套装'}" @click="shopTab='套装'">主题套装 <span>{{page==='shop'?12:outfits.filter(o=>o.id!=='base'&&p.owned.includes(o.id)).length}}</span></button><button :class="{active:shopTab==='配饰'}" @click="shopTab='配饰'">小小配饰 <span>12</span></button></div><div class="filter-row" v-if="shopTab==='套装'"><button v-for="f in ['全部','可爱','神话','三国','科技','幻想']" :key="f" :class="{active:filter===f}" @click="filter=f">{{f}}</button></div>
   <div class="product-grid" v-if="shopTab==='套装'"><button v-for="o in filteredOutfits" :key="o.id" class="product-card" :class="{selected:selected===o.id}" @click="selectProduct(o.id)"><div class="product-art" :style="{background:o.color}"><span v-if="p.owned.includes(o.id)" class="owned-tag"><Check :size="12"/>已拥有</span><Avatar :equipment="suit(o.id)" reduced/></div><div class="product-info"><strong>{{o.name}}</strong><span>{{o.id==='iron'?'升级中':p.owned.includes(o.id)?'去搭配':`★ ${o.price}`}}</span></div><small>{{o.series}}系列 · {{o.action.split(' · ')[0]}}</small></button></div>
   <div v-else class="product-grid accessory-grid"><button v-for="a in filteredAccessories" :key="a.id" class="product-card" :class="{selected:selected===a.id}" @click="selectProduct(a.id)"><div class="accessory-art"><img :src="`/art/rig/accessories/${a.id}.webp`" :alt="a.name" loading="lazy"/><span v-if="p.owned.includes(a.id)" class="owned-tag">已拥有</span></div><div class="product-info"><strong>{{a.name}}</strong><span>★ {{a.price}}</span></div><small>{{slotNames[a.slot]}}</small></button></div><div v-if="page==='wardrobe'&&((shopTab==='套装'&&!filteredOutfits.length)||(shopTab==='配饰'&&!filteredAccessories.length))" class="empty-state"><Gift :size="40"/><h3>这里等着你的第一件收藏</h3><button class="btn primary" @click="!p.tutorial&&user?tutorialOpen=true:navigate('shop')">{{!p.tutorial&&user?'领取教学礼物':'去商城看看'}}</button></div>
  </section></div>
 </main>

 <main v-else-if="page==='game'" class="game-page">
  <div class="game-top"><button class="btn light" @click="navigate('home')"><ArrowLeft :size="18"/>暂存并返回</button><div><span>第 {{c?.level}} 关</span><h2>{{modeNames[mode]}}</h2></div><span class="question-count">{{Math.min(8,(c?.index||0)+1)}} <small>/ 8 题</small></span></div><div class="question-progress"><i :style="{width:(c?.index||0)/8*100+'%'}"></i></div>
  <div v-if="q" class="game-board" :class="[`mode-${mode}`,{'answer-celebration':correctAnimation}]"><div class="game-instruction"><span>{{['找到举着正确答案的小地鼠','答出口诀，给魔法棒充能','补上数字，帮冒险家搭桥','算一算，小客人一共需要多少块甜品'][mode]}}</span><h1 v-if="mode!==3">{{q.a}} × {{mode===2?'□':q.b}} <span>=</span> {{mode===2?q.product:'？'}}</h1><h1 v-else class="story-question">每盒 <b>{{q.a}}</b> 块，装 <b>{{q.b}}</b> 盒<br><small>一共需要多少块小蛋糕？</small></h1></div>
   <div class="play-scene" :class="`scene-${mode}`">
    <div class="playing-avatar"><Avatar :equipment="p.equipment" :perform="perform" :emotion="avatarEmotion" :reaction="reaction" :reduced="p.settings.reducedMotion" mini/></div>
    <div v-if="mode===0" class="mole-field"><button v-for="(n,i) in q.options" :key="q.id+'-'+n" class="mole-target" :class="{correct:correctAnimation&&lastAnswer===n}" :disabled="busy||correctAnimation" :aria-label="`答案 ${n}`" @click="answer(n)"><span v-if="correctAnimation&&lastAnswer===n" class="toy-hammer">🔨</span><div class="mole-hole"></div><div class="mole-creature"><span class="mole-ears">● ●</span><span class="mole-face">• ᴗ •</span><span class="answer-sign">{{n}}</span></div><span class="grass" :style="{transform:`rotate(${i*8-8}deg)`}">🌿</span></button></div>
    <div v-else-if="mode===1" class="battle-field"><div v-if="correctAnimation" class="projectile" :class="'projectile-'+getOutfit(p.equipment.hand).effect">{{getOutfit(p.equipment.hand).icon}}</div><div class="gummy" :class="{hit:correctAnimation}"><span class="gummy-crown">✧</span><span>• ᴗ •</span><small>软糖守护者</small></div><div class="shield"><i v-for="n in 8" :key="n" :class="{gone:n<=(c?.index||0)}"></i></div></div>
    <div v-else-if="mode===2" class="bridge-field"><div class="cloud-platform">☁</div><div class="bridge-gap">{{correctAnimation?lastAnswer:'?'}}<span>放上正确的桥块</span></div><div class="cloud-platform end">☁<span>🚩</span></div><div class="bridge-options"><button v-for="n in q.options" :key="q.id+'-'+n" :disabled="busy||correctAnimation" @click="answer(n)">{{n}}</button></div></div>
    <div v-else class="bakery-field"><span class="bakery-awning"></span><div class="cake-boxes"><span v-for="n in Math.min(q.b||1,9)" :key="n" class="cake-box"><i v-for="j in q.a" :key="j">🧁</i></span></div><div class="bakery-customer">🐰<span>{{correctAnimation?'谢谢你！':'我的甜品好了吗？'}}</span></div></div>
   </div>
   <div class="answer-panel" v-if="mode===1||mode===3"><label class="answer-input"><span>我的答案</span><input aria-label="我的答案" v-model="input" inputmode="numeric" autocomplete="off" maxlength="2" @input="input=input.replace(/\D/g,'').slice(0,2)" @keydown.enter="input&&answer(Number(input))" :disabled="busy||correctAnimation" placeholder="?"/><button class="btn primary" :disabled="!input||busy||correctAnimation" @click="answer(Number(input))">{{mode===1?'施放魔法':'完成订单'}}<Sparkles :size="18"/></button></label><div class="number-pad"><button v-for="n in ['1','2','3','4','5','6','7','8','9','0','⌫']" :key="n" :disabled="busy||correctAnimation" @click="digit(n)">{{n}}</button></div></div>
   <div class="game-feedback" aria-live="polite" :class="{'good':correctAnimation}">{{feedback||'不着急，想好了再回答。'}}<button @click="hint()" :disabled="busy||correctAnimation"><BookOpen :size="16"/>给我一点提示</button></div>
   <div v-if="q.hint" class="hint-box"><strong>{{口诀(q.a,q.b||1)}}</strong><span>{{q.a}} 个一组，共 {{q.b}} 组，合起来是 {{q.a*(q.b||1)}}。</span><div class="hint-groups"><span v-for="n in q.b" :key="n"><i v-for="j in q.a" :key="j">●</i></span></div><small>{{mode===2?`所以空格里填 ${q.b}`:'看着图，再把答案告诉我吧。'}}</small></div>
  </div><div v-else class="pending-settle"><Trophy :size="60"/><h2>这一关的题目完成啦！</h2><button class="btn primary" :disabled="busy" @click="finishPending()">领取通关奖励</button></div>
 </main>

 <main v-else-if="page==='result'" class="result-page"><div class="result-card"><span class="eyebrow">又向前迈进了一小步</span><h1>通关啦，冒险家！</h1><div class="result-stars"><Star v-for="i in 3" :key="i" :class="{lit:i<=(c?.result?.stars||1)}" :size="58" fill="currentColor" :style="{'--i':i}"/></div><Avatar :equipment="p.equipment" :perform="perform" :emotion="avatarEmotion" :reaction="reaction" :reduced="p.settings.reducedMotion" mini/><h2>你独立完成了 {{c?.result?.correct}} 道题</h2><p>{{c?.result?.correct===8?'每一道都答对了，你的努力闪闪发光！':'坚持完成挑战，就是很棒的进步。下次再一起练习！'}}</p><div class="reward-details"><span>首次答对 <b>+{{(c?.result?.correct||0)*2}}</b></span><span>完成挑战 <b>+10</b></span><span v-if="c?.result?.firstClear">首次通关 <b>+10</b></span><span v-if="c?.result?.starBonus">首次三星 <b>+5</b></span></div><div class="reward-total">★ +{{c?.result?.coins}} <small>星星币已放进口袋</small></div><div v-if="roundCompletions%3===0" class="rest-note">🌱 已经完成 3 关啦，站起来看看远处吧。</div><div class="result-buttons"><button class="btn light" @click="navigate('shop')"><Gift :size="18"/>去挑奖励</button><button class="btn primary" @click="start(Math.min(18,(c?.level||1)+1))">{{c?.level===18?'再来一场':'下一场冒险'}}<ChevronRight :size="18"/></button></div><button class="wish-button" @click="navigate('home')">回到冒险地图</button></div></main>

 <main v-else-if="page==='parent'" class="parent-page"><div class="page-heading"><div><span class="eyebrow">陪伴每一次小小成长</span><h1>家长中心</h1><p>{{user?.email}} · 记录练习过程，不用速度衡量孩子。</p></div><button class="btn light" @click="logout()"><LogOut :size="17"/>退出账号</button></div><div class="parent-stats"><div><strong>{{Object.keys(p.stars).length}}</strong><span>已通关 / 18</span></div><div><strong>{{mastery.length}}</strong><span>口诀已熟悉</span></div><div><strong>{{weak.length}}</strong><span>口诀待巩固</span></div><div><strong>{{p.history.length}}</strong><span>近期完成挑战</span></div></div><div class="parent-grid"><section class="parent-panel"><h2>口诀练习地图</h2><p>同一口诀在两次挑战中累计独立答对 3 次，最近两次正确，标为已熟悉。</p><div class="mastery-legend"><span class="mastered">已熟悉</span><span class="practiced">已练习</span><span class="weak">待巩固</span><span>未练习</span></div><div class="fact-grid"><template v-for="a in 9" :key="a"><button v-for="b in 9" :key="b" :class="factStatus(a,b)" :title="口诀(a,b)">{{a}}×{{b}}</button></template></div></section><section class="parent-panel"><h2>最近的练习</h2><div v-if="!p.history.length" class="empty-text">第一场冒险结束后，记录会出现在这里。</div><el-table v-else :data="p.history.slice(0,8)" style="width:100%"><el-table-column label="关卡"><template #default="scope">第 {{scope.row.level}} 关</template></el-table-column><el-table-column label="独立正确"><template #default="scope">{{scope.row.correct}} / 8</template></el-table-column><el-table-column label="日期"><template #default="scope">{{new Date(scope.row.at).toLocaleDateString('zh-CN')}}</template></el-table-column></el-table><div class="setting-row"><div><strong>游戏音效</strong><small>答对、通关和换装的小小庆祝</small></div><el-switch :model-value="p.settings.sound" :disabled="busy" @change="settings('sound')" aria-label="游戏音效"/></div><div class="setting-row"><div><strong>减少动效</strong><small>保留静态反馈，减少大幅运动</small></div><el-switch :model-value="p.settings.reducedMotion" :disabled="busy" @change="settings('reducedMotion')" aria-label="减少动效"/></div></section></div></main>

 <el-dialog v-model="auth" :title="authMode==='register'?'给冒险安一个家':authMode==='forgot'?'找回密码':authMode==='reset'?'设置新密码':'欢迎回到星星乘法岛'" width="420px" :close-on-click-modal="false"><form class="auth-form" @submit.prevent="submitAuth"><p>家长账号保存进度，换一台电脑也能接着玩。</p><label v-if="authMode==='register'">冒险家昵称<el-input v-model="nickname" maxlength="16" placeholder="小冒险家"/></label><label v-if="authMode!=='reset'">家长邮箱<el-input v-model="email" type="email" autocomplete="email" placeholder="your@email.com" required/></label><label v-if="authMode!=='forgot'">密码<el-input v-model="password" type="password" show-password :autocomplete="authMode==='login'?'current-password':'new-password'" placeholder="8～72 个字符" required/></label><p v-if="authMessage" class="auth-message">{{authMessage}}</p><p v-if="error" class="auth-error">{{error}}</p><button class="btn primary full" :disabled="busy" type="submit">{{busy?'正在连接…':authMode==='register'?'创建账号，开始冒险':authMode==='forgot'?'发送重置邮件':authMode==='reset'?'更新密码':'登录'}}</button><div class="auth-links"><button type="button" @click="authMode=authMode==='register'?'login':'register';error=''">{{authMode==='register'?'已有账号？去登录':'没有账号？免费注册'}}</button><button v-if="authMode==='login'" type="button" @click="authMode='forgot';error=''">忘记密码</button></div><small v-if="authMode==='forgot'&&!resetAvailable">当前尚未配置邮件服务，暂时无法发送重置邮件。</small></form></el-dialog>
 <el-dialog v-model="tutorialOpen" title="第一次冒险，先认识一下" width="650px" :close-on-click-modal="false"><div v-if="tutorialStep===0" class="tutorial"><span class="tutorial-art">🥕 🥕<br>🥕 🥕<br>🥕 🥕</span><h2>每组 2 个萝卜，有 3 组</h2><p>2 + 2 + 2，也可以写成 2 × 3。</p><div class="tutorial-options"><button v-for="n in [5,6,8]" :key="n" class="btn light" @click="tutorialAnswer=n===6;!tutorialAnswer&&notice('一起数数这六个萝卜吧')">{{n}}</button></div><p v-if="tutorialAnswer" class="success-text">答对啦！二三得六。答对会有奖励，答错可以再试。</p><button class="btn primary" :disabled="!tutorialAnswer" @click="tutorialStep=1;sound()">领取我的第一套外观<Gift :size="18"/></button></div><div v-else class="tutorial"><h2>选一位伙伴，陪你一起长大</h2><p>四套任选一套，免费送给勇敢出发的你。</p><div class="free-suits"><button v-for="o in outfits.filter(x=>x.series==='可爱')" :key="o.id" :class="{selected:freeSuit===o.id}" @click="freeSuit=o.id"><Avatar :equipment="suit(o.id)" reduced/><strong>{{o.name}}</strong></button></div><button class="btn primary" :disabled="busy" @click="finishTutorial()">就选{{getOutfit(freeSuit).name}}！<Sparkles :size="18"/></button></div></el-dialog>
 <el-dialog :model-value="selectedLevel!==null" @update:model-value="selectedLevel=null" :title="selectedInfo?.name||'冒险关卡'" width="460px"><div class="level-dialog" v-if="selectedInfo"><p>这座小岛有两场冒险，先学新口诀，再一起巩固。</p><button v-for="l in levels.filter(x=>x.island===selectedInfo!.island)" :key="l.id" class="level-row" :disabled="l.id>unlocked||busy" @click="start(l.id)"><span class="level-icon">{{l.mode===4?'🌟':modeIcons[l.mode]}}</span><span><strong>第 {{l.id}} 关 · {{l.mode===4?'星星庆典':modeNames[l.mode]}}</strong><small>{{l.review?'口诀复习':'新的口诀'}} · {{p.stars[l.id]?'★'.repeat(p.stars[l.id]!):'等待你的脚印'}}</small></span><Lock v-if="l.id>unlocked" :size="18"/><Play v-else :size="18"/></button></div></el-dialog>
 <div v-if="transform" class="transformation" :class="{gift}" role="status" @click="transform=false;gift=false"><div class="transform-rays"></div><div class="transform-content"><div v-if="gift" class="gift-title">🎁 新外观到手啦！</div><Avatar :equipment="p.equipment" :perform="perform" :emotion="avatarEmotion" :reaction="reaction" :reduced="p.settings.reducedMotion"/><h1>{{completeOutfit(p.equipment)==='mixed'?'专属造型':currentOutfit.name}}，登场！</h1><p>这是你努力获得的小小闪光</p><button>点击任意位置继续</button></div></div>
 <div v-if="toast" class="toast" role="status"><Sparkles :size="18"/>{{toast}}</div>
</div>
</template>
